server_run:
	go run cmd/main.go
#mock:
#	~/go/bin/mockgen -source=internal/interface/repository/user_repository.go -destination=./internal/mock/male_mock.go -package=mock
mockUser:
	~/go/bin/mockgen -source=internal/usecase/repository/user_repository.go -destination=./internal/mock/usecase_user_repository.go -package=mock
